# Generated by Django 6.0.2 on 2026-02-12 15:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LevelThreshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_number', models.PositiveIntegerField(unique=True, verbose_name='Номер уровня')),
                ('xp_required', models.PositiveIntegerField(verbose_name='Необходимо XP')),
            ],
            options={
                'verbose_name': 'Порог уровня',
                'verbose_name_plural': 'Пороги уровней',
            },
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст цитаты')),
                ('author', models.CharField(max_length=200, verbose_name='Автор')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Цитата',
                'verbose_name_plural': 'Цитаты',
            },
        ),
        migrations.CreateModel(
            name='Dependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название зависимости')),
                ('slug', models.SlugField(unique=True, verbose_name='URL-идентификатор')),
                ('description', models.TextField(verbose_name='Описание зависимости')),
                ('is_preset', models.BooleanField(default=True, verbose_name='Предустановленная зависимость')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создано пользователем')),
            ],
            options={
                'verbose_name': 'Зависимость',
                'verbose_name_plural': 'Зависимости',
            },
        ),
        migrations.CreateModel(
            name='DependencyLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('light', 'Легкий'), ('medium', 'Средний'), ('heavy', 'Тяжелый')], max_length=10, verbose_name='Уровень')),
                ('days_required', models.PositiveIntegerField(verbose_name='Количество дней для лечения')),
                ('dependency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pro_svet.dependency', verbose_name='Зависимость')),
            ],
            options={
                'verbose_name': 'Уровень зависимости',
                'verbose_name_plural': 'Уровни зависимости',
            },
        ),
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название привычки')),
                ('description', models.TextField(verbose_name='Описание')),
                ('xp_reward', models.PositiveIntegerField(default=10, verbose_name='Награда за выполнение')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Полезная привычка',
                'verbose_name_plural': 'Полезные привычки',
            },
        ),
        migrations.CreateModel(
            name='UserDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Завершена')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Дата начала лечения')),
                ('last_day_of_abstinence', models.DateField(blank=True, null=True, verbose_name='Последний день воздержания')),
                ('current_streak', models.PositiveIntegerField(default=0, verbose_name='Текущая серия дней')),
                ('total_days_abstained', models.PositiveIntegerField(default=0, verbose_name='Всего дней воздержания')),
                ('relapse_count', models.PositiveIntegerField(default=0, verbose_name='Количество срывов')),
                ('dependency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pro_svet.dependency', verbose_name='Зависимость')),
                ('level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pro_svet.dependencylevel', verbose_name='Уровень зависимости')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Пользовательская зависимость',
                'verbose_name_plural': 'Пользовательские зависимости',
                'unique_together': {('user', 'dependency')},
            },
        ),
        migrations.CreateModel(
            name='Relapse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата срыва')),
                ('reason', models.TextField(blank=True, verbose_name='Причина срыва')),
                ('user_dependency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pro_svet.userdependency', verbose_name='Зависимость пользователя')),
            ],
            options={
                'verbose_name': 'Срыв',
                'verbose_name_plural': 'Срывы',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xp', models.IntegerField(default=0, verbose_name='Очки опыта')),
                ('level', models.IntegerField(default=0, verbose_name='Уровень просветления')),
                ('quote_notifications_enabled', models.BooleanField(default=True, verbose_name='Уведомления с цитатами')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
            },
        ),
        migrations.CreateModel(
            name='HabitCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата выполнения')),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pro_svet.habit', verbose_name='Привычка')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Выполнение привычки',
                'verbose_name_plural': 'Выполнения привычек',
                'unique_together': {('habit', 'date')},
            },
        ),
        migrations.CreateModel(
            name='DailyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('is_abstinent', models.BooleanField(default=False, verbose_name='Было воздержание')),
                ('note', models.TextField(blank=True, verbose_name='Заметка')),
                ('user_dependency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pro_svet.userdependency', verbose_name='Зависимость пользователя')),
            ],
            options={
                'verbose_name': 'Ежедневная запись',
                'verbose_name_plural': 'Ежедневные записи',
                'unique_together': {('user_dependency', 'date')},
            },
        ),
    ]
