# Generated by Django 5.2.7 on 2026-02-12 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro_svet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='auto_continue_streak',
            field=models.BooleanField(default=False, verbose_name='Автоматически продлевать серию'),
        ),
    ]
